from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from Test_Data import project_4
import pytest
import time 

class Test_Project_4:
    url = "https://qa.makerble.com/users/sign_up " 

    @pytest.fixture
    def booting_function(self):
        self.driver = webdriver.Edge()
        yield
        self.driver.close() 
        
    def test_form(self,booting_function):
        
        self.driver.maximize_window()
        self.driver.get(self.url)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.signin_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_email_xpath).send_keys(project_4.Project_Data_1.user_email)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_password_xpath).send_keys(project_4.Project_Data_1.user_password)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.login_signin_xpath).click()
        time.sleep(6)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.myapps_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.contactform_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.newcontact_xpath).click()
        time.sleep(2) 
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.contactform_name_xpath).send_keys(project_4.Project_Data_1.contact_form_name)
        time.sleep(2) 
        self.driver.find_element(by=By.XPATH, value='//*[@id="c2-0i"]').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="save_btn"]').click()
        time.sleep(10)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.edit_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.create_field_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.name_of_field_xpath).send_keys(project_4.Project_Data_1.name_of_field)
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.reason_xpath).send_keys(project_4.Project_Data_1.reason)
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="submitCustomFieldBtn"]').click()
        time.sleep(3)
          
    def test_patientform(self,booting_function):
        
        self.driver.maximize_window()
        self.driver.get(self.url)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.signin_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_email_xpath).send_keys(project_4.Project_Data_1.user_email)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_password_xpath).send_keys(project_4.Project_Data_1.user_password)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.login_signin_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.proj_pref_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.preferences_xpath).click()
        time.sleep(10)
        ele = self.driver.find_element(by=By.XPATH, value='//*[@id="s2id_contact-forms-select2"]/ul')
        ele.click()
        for i in range(1):
            ele.send_keys(Keys.ARROW_DOWN)
        ele.send_keys(Keys.ENTER) 
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="project_preferences_form"]/div[1]/div[4]/div/div/table/tbody/tr[2]/td[3]/input[1]').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="project_preferences_form"]/div[1]/div[4]/div/div/table/tbody/tr[3]/td[3]/input[1]').click()
        time.sleep(2)
        self.driver.find_element(by=By.ID, value='enable-waiting-list-state-checkbox').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="enable-waiting-list-state-contact-form-checkbox"]').click()
        time.sleep(2)
        s = Select(self.driver.find_element(by=By.XPATH, value='//*[@id="waiting-list-state-contact-form-select"]'))
        s.select_by_visible_text('Patients')
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="enable-waiting-list-state-public-referral-link-checkbox"]').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.declined_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.alumini_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.event_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.cases_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="launch_create_page"]').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.stories_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.financial_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.timesheet_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="preferences-save-btn"]').click()
        time.sleep(2) 
    
    def test_mentalassesment(self,booting_function):
        
        self.driver.maximize_window()
        self.driver.get(self.url)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.signin_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_email_xpath).send_keys(project_4.Project_Data_1.user_email)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_password_xpath).send_keys(project_4.Project_Data_1.user_password)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.login_signin_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.explore_xpath).click()
        time.sleep(3) 
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.addproject_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.ID, value=project_4.project_Selector_2.counselling_xpath).click()
        time.sleep(4)
        self.driver.find_element(by=By.XPATH, value='//*[@id="link_to_projects"]/div/div[2]/a[2]').click()
        time.sleep(3)
        
    def test_contact(self,booting_function):
        
        self.driver.maximize_window()
        self.driver.get(self.url)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.signin_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_email_xpath).send_keys(project_4.Project_Data_1.user_email)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_password_xpath).send_keys(project_4.Project_Data_1.user_password)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.login_signin_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.more_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_header_div"]/div[1]/div[2]/ul[2]/li[7]/ul/li[1]/a').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_body_div"]/div/div[4]/div/div/div/div/div/div/div[1]/div[2]/div/div/div[2]/a[2]').click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.moreoptions_xpath).click()
        time.sleep(7)
        e=self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.publicform_xpath)
        e.click()
        for i in range(12):
            e.send_keys(Keys.ARROW_DOWN)
            if i==11:
                e.send_keys(Keys.ENTER)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_body_div"]/div/div[1]/div/div/div[3]/a[4]').click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_body_div"]/div/div[3]/div[2]/div[2]/div/div[1]/label/input').click() 
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.nameof_form_xpath).send_keys('Potential Patients')
        time.sleep(3)
        s = Select(self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.proj_selection_xpath))
        s.select_by_visible_text('Counselling')
        time.sleep(2)
        s_2 = Select(self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.state_xpath))
        s_2.select_by_visible_text('Waiting List')
        time.sleep(2)
        s_1= Select(self.driver.find_element(by=By.XPATH, value='//*[@id="referral_link_detail_contact_form_select"]'))
        s_1.select_by_visible_text('Patients')
        time.sleep(2)
        s_3= Select(self.driver.find_element(by=By.XPATH, value='//*[@id="beneficiary_types_select"]'))
        s_3.select_by_visible_text('Person')
        time.sleep(10)
        s_4=self.driver.find_element(by=By.XPATH, value='//*[@id="s2id_autogen1"]')
        s_4.click()
        for i in range(1):
            s_4.send_keys(Keys.ARROW_DOWN)
        s_4.send_keys(Keys.ENTER)
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="referral_link_detail-save-btn"]').click()
        time.sleep(4) 
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.copy_link_xpath).click() 
        time.sleep(5)
        print("link copied") 
          
    def test_referral(self,booting_function):
        
        self.driver.maximize_window()
        self.driver.get('https://qa.makerble.com/charities/430/projects/1140/beneficiaries/new?referral_link_detail_id=91')
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.nameof_contact_xpath).send_keys('Jhony')
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="beneficiary_submit_btn"]').click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.story_xpath).send_keys(project_4.Project_Data_1.story)
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.location_xpath).send_keys(project_4.Project_Data_1.location)
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="publish"]')
        time.sleep(3)
        
    def test_final(self,booting_function):
        
        self.driver.maximize_window()
        self.driver.get(self.url)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.signin_xpath).click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_email_xpath).send_keys(project_4.Project_Data_1.user_email)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.user_password_xpath).send_keys(project_4.Project_Data_1.user_password)
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.Project_Selector_1.login_signin_xpath).click()
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.more_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_header_div"]/div[1]/div[2]/ul[2]/li[7]/ul/li[1]/a').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_body_div"]/div/div[4]/div/div/div/div/div/div/div[1]/div[2]/div/div/div[2]/a[2]').click()
        time.sleep(3)
        self.driver.find_element(by=By.XPATH, value=project_4.project_Selector_2.filter_xpath).click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_body_div"]/div[3]/div[3]/div/div[3]/div[4]/div[2]/input').click()
        time.sleep(2)
        self.driver.find_element(by=By.XPATH, value='//*[@id="main_body_div"]/div[3]/div[3]/div/div[3]/div[1]/div/span[2]').click()
        time.sleep(5)
